'use strict';
const whatsappNumber='5547988378931';
document.querySelectorAll('.wa-link').forEach(link=>{const model=link.dataset.model;const message=model?`Olá! Vim pelo site da Stop Baby e gostaria de um orçamento de ${model} para minha empresa.`:'Olá! Vim pelo site da Stop Baby e gostaria de um orçamento de uniformes para minha empresa.';link.href=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;});
const toggle=document.querySelector('.menu-toggle');const menu=document.querySelector('#mobile-nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');menu.hidden=!open;});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menu');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menu');toggle.focus();}});
const galleryButtons=[...document.querySelectorAll('[data-photo]')];
let filteredPhotos=galleryButtons;let activePhoto=0;let lastPhotoButton;
const lightbox=document.querySelector('#lightbox');const lightboxImage=document.querySelector('.lightbox-image');
function showPhoto(index){activePhoto=(index+filteredPhotos.length)%filteredPhotos.length;const button=filteredPhotos[activePhoto];lightboxImage.src=button.dataset.photo;lightboxImage.alt=button.dataset.caption;document.querySelector('#lightbox-caption').textContent=button.dataset.caption;document.querySelector('.lightbox-counter').textContent=`${activePhoto+1} / ${filteredPhotos.length}`;document.querySelector('.lightbox-quote').href=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent('Olá! Vim pelo site da Stop Baby e gostaria de um orçamento. Tenho interesse neste modelo: '+button.dataset.caption+'.')}`;}
galleryButtons.forEach(button=>button.addEventListener('click',()=>{lastPhotoButton=button;showPhoto(filteredPhotos.indexOf(button));lightbox.showModal();document.body.classList.add('modal-open');}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const category=button.dataset.filter;galleryButtons.forEach(photo=>{photo.hidden=category!=='todos'&&photo.dataset.category!==category;});filteredPhotos=galleryButtons.filter(b=>!b.hidden);document.querySelector('.gallery-count').textContent=`${filteredPhotos.length} ${filteredPhotos.length===1?'foto':'fotos'}`;}));
document.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());document.querySelector('.lightbox-prev').addEventListener('click',()=>showPhoto(activePhoto-1));document.querySelector('.lightbox-next').addEventListener('click',()=>showPhoto(activePhoto+1));lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(activePhoto-1);}if(e.key==='ArrowRight'){e.preventDefault();showPhoto(activePhoto+1);}});lightbox.addEventListener('click',e=>{if(e.target===lightbox){const r=lightbox.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)lightbox.close();}});lightbox.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastPhotoButton?.focus();});document.querySelector('#year').textContent=new Date().getFullYear();
